### ISSUE TITLE
Investigate "New Dawn" for worldgen engine

### ISSUE THREAD

**Issue by PaintNinja** [PaintNinja/CraftMine#3]
I noticed that EBXL supports "New Dawn" - a world generation engine that completely changes the default world generation rules and mechanics of the game.

It'll be great to see if this would be a good idea to add and if it supports both Highlands and EBXL without having too many lag spikes or bugs.

Also, it'll be interesting to see how much this changes the terrain. Does it change it a lot or is it more like MC1.8? Is it similar to current CMv3 generation where it's very mountainous but not very flat at all when high up?

Link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1283481-1-7-10-forge-new-dawn-completely-new-terrain

**Comment by Pikachu298** [comment]
Testing "New Dawn" along with "ExtraBiomesXL" and "YAMPST", while providing 1500MB of maximum RAM turned out to work like a charm. Only small lag spikes while Sprint-Flying when it generates an EBXL Huge Tree.

Attached Screenshots show the beautiful generated world, which was caused by New Dawn. Some very nice Hill areas are being generated, while there are very long flat areas too. It's not soo similar to v3 and MC1.8, but looks pretty badass.

![2015-09-21_15 01 27](https://cloud.githubusercontent.com/assets/14407620/9992381/03e6c71c-6072-11e5-93a8-1e0067def34f.png)
![2015-09-21_15 00 29](https://cloud.githubusercontent.com/assets/14407620/9992383/0405798c-6072-11e5-9135-c14fd284269f.png)
![2015-09-21_15 02 26](https://cloud.githubusercontent.com/assets/14407620/9992384/04209c94-6072-11e5-88ac-c9cbbf450c8e.png)

**Comment by Pikachu298** [comment]
Seemed to fix the small lag spikes by turning the render distance down to 11 Chunks

**Comment by PaintNinja** [comment]
Thank you for your investigation. It's great to hear that New Dawn is stable and produces some nice results!

Is it possible to make flat areas rare in New Dawn?

**Comment by Pikachu298** [comment]
Going to take a look at it in the evening ;)
The flat areas aren't Thaaaat common either.

**Comment by Pikachu298** [comment]
Unfortunately there is not a single option in the configs which will turn off the massive flat areas. The config file only maintains Thaumcraft support.

**Comment by PaintNinja** [comment]
Ahh that's a shame... Have you tried turning off vanilla plains biomes in the Highlands config and then making a new world with New Dawn in it too?

**Comment by Pikachu298** [comment]
Oooh. I'll look into that later this evening!

**Comment by Pikachu298** [comment]
Not Implemented due to massive flat areas which are bigger than +200 blocks, and massive completely frozen oceans which are about the same size, if not bigger. Sadly it doesn't add many mountains.

**Comment by PaintNinja** [comment]
Ah, that's a big shame... :(

Thank you for looking into this, I knew it wouldn't be easy.
